on: [push]

jobs:
  archi_report:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    name: Deploy Archi report HTML to GitHub Pages
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Deploy Archi report
        id: archi
        uses: WoozyMasta/archimate-ci-image@4.9.1-1.0.1
        with:
          archiHtmlReportEnabled: true
          githubPagesBranch: docs
          archiJasperReportEnabled: false
          archiJasperReportFormats: PDF,DOCX
          archiCsvReportEnabled: false
          archiExportModelEnabled: false
          githubToken: ${{ secrets.GITHUB_TOKEN }}
